---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: foundation
spec:
  podSecurityContext: 
    runAsUser: 1000   
    fsGroup: 1000
  kubernetesConfig:   
    image: redis:8-bookworm
    resources:
      requests:
        cpu: 101m
        memory: 128Mi 
      limits:
        cpu: 101m
        memory: 128Mi 
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.44.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi 
      limits:
        cpu: 100m
        memory: 128Mi 
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:  
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:   
            storage: 1Gi
